name: lightning
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.12
  - numpy=2.1.2
  - pytorch=2.4.1
  - gymnasium[all]=1.0.0
  - torch=2.4.1
  - torchvision=2.4.1
  - matplotlib=1.3.0
  - pandas=2.2.3
  - stable-baselines3=2.3.2
  - tqdm=4.66.5
  - pandas=2.2.3
